athos777x/system

- package-lock.json
- package.json
- src/RoleSidebars/ClassAdviserSideBar.js
> Athostestcodes

- src/RegistrarPages/Registrar_StudentsPage.js
Modify student view and edit button visibility based on user role
> Modify student view and edit button visibility based on user role

- src/RegistrarPages/Registrar_TeacherPage.js
- src/RegistrarPagesCss/Registrar_StudentsPage.css
> edit button added

- src/RegistrarPages/Registrar_SectionPage.js
removed permission for add new section and edit section for academic coordinator
> Implement role-based access control for Section Management page

- src/PrincipalPages/Principal_SchedulePage.js
- src/RoleSearchFilters/ScheduleSearchFilter.js
added school year filter for schedule page
> added school year filter for schedule page

- backend/server.js
- src/PrincipalPages/Principal_SchedulePage.js
changed teacher id to teacher name in schedule page
> changed teacher id to teacher name in schedule page

- src/CssPage/Principal_SchedulePage.css
- src/PrincipalPages/Principal_SchedulePage.js
Improve modal button styling and layout in Schedule Page
> Improve modal button styling and layout in Schedule Page

- src/RegistrarPages/Registrar_GradesPage.js
- src/RoleSearchFilters/student_grades_search.js
- src/Utilities/grades-detail.js
- Introduced Student_Grades_Search component for dynamic student search
- Added role-based access control for grades editing and submission
- Implemented user role fetching from backend
- Enhanced grades page with more flexible student and grades retrieval
- Added filtering and detailed view options for grades
> Add role-based access control and student grades search functionality

- backend/server.js
- Add role-based user account creation during employee registration
- Retrieve role_id dynamically when adding a new employee
- Generate default username based on employee name
- Create user account with default password and role information
> Enhance employee creation with automatic user account generation

- backend/server.js
- src/PrincipalPages/Principal_SubjectsPage.js
- Add school year status to subjects query in backend
- Disable subject archiving when subject status is active
- Prevent archiving of active subjects in Principal Subjects Page
> Enhance subject archiving and query with school year status

- src/CssPage/Principal_SchedulePage.css
- src/PrincipalPages/Principal_SchedulePage.js
- Add multi-day checkbox selection for schedules
- Implement day sorting and parsing for consistent display
- Update CSS for day checkboxes with improved styling
- Refactor schedule creation and editing to support multiple days
- Add error handling for day parsing and schedule management
> Enhance schedule management with multi-day selection and improved UI

- backend/server.js
- Update subjects endpoint to alias school year status column for clarity
- Modify subject status update query to handle active and inactive school years dynamically
- Correct case sensitivity in section students name column retrieval
- Enhance error messages and response handling in subject status update endpoint
> Refactor Subjects and Section Endpoints with Improved Query Handling

- backend/server.js
- src/RegistrarPages/Registrar_TeacherPage.js
- Implement school year dropdown in teacher assignment modals
- Update backend endpoints to support school year ID in subject and section assignments
- Fetch and auto-select active school year by default
- Add validation to ensure school year is selected before assignment
- Modify frontend and backend queries to include school year context
> Add School Year Selection to Teacher Subject and Section Assignment

- backend/server.js
- Migrate server configuration from React component to Express.js backend
- Implement comprehensive server-side routing for various application features
- Add endpoints for user authentication, student management, enrollment, and grades
- Integrate database queries with MySQL for dynamic data retrieval and manipulation
- Enhance error handling and logging across server endpoints
> Refactor Server Configuration and Add Comprehensive Backend Endpoints

- src/RegistrarPages/Registrar_AttendancePage.js
- Add default attendance data when no records are found
- Enhance error handling in attendance data fetching
- Add grade level and school year header to attendance table
- Implement null-safe rendering of attendance details
- Add fallback values for missing attendance data
> Improve Registrar Attendance Page Error Handling and UI

- src/CssFiles/form_137.css
- src/CssFiles/form_138.css
- Adjust font size for table cells in Form 137
- Change table header background color to green (#28a745) in Form 138
- Enhance visual consistency of attendance tables across forms
> Update Attendance Table Styling in Form 137 and Form 138

- backend/server.js
- src/PrincipalPages/Principal_SchedulePage.js
- src/PrincipalPages/test_subjectsPage.js
- src/RegistrarPages/grades_page.js
- Refactor grades page to support dynamic student filtering
- Implement grade editing functionality with save and cancel options
- Add pagination support for student list
- Improve grade calculation and display logic
- Enhance user interaction for viewing and editing student grades
> Enhance Grades Page with Dynamic Filtering and Editing Capabilities

- src/RegistrarPagesCss/Registrar_StudentsPage.css
- Include styling for print button with hover effects
- Add specific styling for archive button with distinctive color scheme
- Maintain consistent button design across different action buttons
> Add Print and Archive Button Styles to Students Page CSS

- src/RoleSearchFilters/EmployeeSearchFilter.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/StudentManagement.js
- Change position filter value from 'teacher' to 'subject_teacher' in EmployeeSearchFilter
- Modify StudentManagement section filtering to use section_name instead of section_id
- Refactor section filter logic to match updated data structure
> Update Employee Search Filter and Student Management Filtering

- src/RoleSidebars/ClassAdviserSideBar.js
- src/RoleSidebars/GradeLevelCoordinatorSideBar.js
- src/RoleSidebars/PrincipalSideBar.js
- src/RoleSidebars/SubjectCoordinatorSideBar.js
- src/RoleSidebars/SubjectTeacherSideBar.js
- src/TeacherPages/PromotionReport.js
- src/TeacherPages/TestGradesManagement.js
- Update ClassAdviser, GradeLevelCoordinator, Principal, SubjectCoordinator, and SubjectTeacher sidebars to include new navigation options for 'New Grades' and 'Brigada Eskwela'.
- Refactor submenu logic to improve user experience and streamline navigation.
- Implement role-based visibility for various report generation options in PromotionReport and TestGradesManagement components, ensuring appropriate access based on user roles.
- Add role fetching functionality to dynamically adjust UI elements based on user permissions.
> Enhance Role Sidebars and Promotion Report Functionality

- backend/server.js
- src/App.js
- src/RoleSidebars/RegistrarSideBar.js
- src/TeacherPages/ElectiveRequest.js
- src/TeacherPages/TeacherManagement.js
- Updated the enrollment validation endpoint to handle both approval and rejection actions, allowing for more flexible student enrollment management.
- Modified the frontend to support the new validation logic, including changes to the EnrollmentRequests component for improved user interaction.
- Added a new route for pending elective requests and updated the sidebar to include navigation to this feature.
- Improved error handling and logging for better debugging and user feedback during enrollment processes.
> Enhance Enrollment and Elective Management Features

- backend/server.js
- src/RoleSearchFilters/StudentSearchFilter.js
- src/RoleSidebars/RegistrarSideBar.js
- src/TeacherPages/StudentManagement.js
- Added searchID parameter to the student retrieval endpoint for direct student lookups.
- Improved handling of school year selection, defaulting to the active school year if not provided.
- Refactored SQL queries to ensure proper filtering and sorting of student data.
- Integrated a new StudentSearchFilter component for enhanced filtering capabilities in the frontend.
- Updated the student management table to display student ID and improved data handling for student details.
- Enhanced error handling and logging for better debugging during student data operations.
> Enhance Student Management and Search Functionality

- backend/server.js
- src/RoleSearchFilters/EmployeeSearchFilter.js
- src/TeacherPages/AttendanceManagement.js
- src/TeacherPages/BrigadaEskwela.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/SectionList.js
- src/TeacherPages/TeacherManagement.js
- Added searchID filter to the EmployeeSearchFilter component for direct employee lookups.
- Updated SQL queries in the backend to include school year in attendance records and improved employee filtering logic.
- Integrated StudentSearchFilter component into AttendanceManagement and BrigadaEskwela pages for enhanced student search capabilities.
- Refactored attendance and grades management tables to display student IDs and names more effectively.
- Improved error handling and logging for better debugging during data operations.
> Enhance Employee and Student Management Functionality

- src/TeacherPages/TeacherManagement.js
- Added a dropdown to select subjects based on the active school year in the Teacher Management component.
- Updated the fetchTeacherSubjects function to accept a school year ID, allowing for dynamic subject retrieval.
- Implemented logic to set the default school year based on the active status.
- Improved UI layout for better clarity and usability in the assigned subjects section.
> Enhance Teacher Management with subject selection by school year

- backend/server.js
- src/TeacherPages/StudentManagement.js
- Added 'emergency_contactperson' field to student data model and forms.
- Updated backend to handle emergency contact information during student creation and updates.
- Improved UI to display and edit emergency contact details in the Student Management component.
> Enhance student management with emergency contact details

- src/TeacherPages/TeacherManagement.js
- Improved styling and layout for the Assign Section modal, including updated colors and spacing for better visual appeal.
- Enhanced the School Year and Grade Level selection with improved button styles and hover effects.
- Added a responsive grid layout for Available Sections, including a message for when no sections are available.
- Updated action buttons with consistent styling and disabled states for better user experience.
> Enhance Assign Section modal in TeacherManagement component

- backend/server.js
- src/StudentPages/Student_EnrollmentPage.js
- src/TeacherPages/AttendanceManagement.js
- Updated the '/enroll-elective' endpoint to validate required fields and check for existing enrollments before processing requests.
- Modified the Student Enrollment Page to fetch student details, including grade level, before submitting enrollment requests.
- Improved error handling and user feedback for elective enrollment submissions.
- Enhanced the Attendance Management component to ensure all required fields are available and displayed correctly, including grade level and attendance status.
> Enhance elective enrollment and student data handling

- backend/server.js
- src/RoleSearchFilters/StudentSearchFilter.js
- src/RoleSidebars/SubjectCoordinatorSideBar.js
- src/StudentPages/Student_GradesPage.js
- src/TeacherPages/EnrolledStudents.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/PromotionReport.js
- Updated API endpoints to include school_year_id for fetching students, subjects, and grades.
- Modified frontend components to handle school year selection and ensure data consistency across various pages.
- Improved filter functionality in StudentSearchFilter and GradesManagement components to incorporate school year as a required parameter.
- Removed unnecessary comments and cleaned up code for better readability.
> Enhance student and grades management with school year integration

- src/CssFiles/headbar.css
- src/Utilities/HeadBar.js
- Introduced a new CSS class for styling user roles in the dropdown menu.
- Updated HeaderBar component to conditionally render the user's role, formatted for better readability.
> Add dropdown role display in HeaderBar component

- src/TeacherPages/BrigadaEskwela.js
- src/TeacherPagesCss/BrigadaEskwela.css
- Updated attendance toggle logic to use student objects instead of IDs for better clarity.
- Enhanced modal for absence reasons with improved styling and user experience.
- Added error handling for attendance updates and improved modal state management.
- Updated CSS for modal and button styles to enhance visual consistency.
> Refactor attendance handling in Brigada Eskwela component

- src/TeacherPages/StudentManagement.js
- Introduced a dropdown for editing student status, allowing selection of 'Active', 'Inactive', 'Withdrawn', or 'Transferred'.
- Enhanced the UI to display the current status when not in editing mode, improving user experience and clarity in student management.
> Add student status selection to Student Management component

- src/TeacherPages/StudentManagement.js
- Moved the student status section to a new position within the UI for better organization.
- Ensured the dropdown for editing student status is displayed correctly when in editing mode, maintaining clarity for users.
- Removed redundant code for the status section to streamline the component.
> Refactor student status display in Student Management component

- backend/server.js
- src/TeacherPages/PromotionReport.js
- src/TeacherPages/StudentManagement.js
- Updated the student management system to include a new LRN field for better student identification.
- Modified the promotion report to validate required fields and fetch student names based on LRN.
- Improved the handling of student data insertion and updates, including the addition of section_id and brigada remarks.
- Refactored query parameters in the student names endpoint to support optional filters for better search functionality.
> Enhance student management and promotion report features

- src/TeacherPages/EnrollmentRequests.js
- src/TeacherPagesCss/EnrollmentRequests.css
- Introduced a new modal for student enrollment that includes a confirmation checkbox for required documents.
- Implemented fetching of subjects and grades for students, displaying previous school year grades in the modal.
- Added logic to handle enrollment based on student grades, including warnings for failed subjects.
- Enhanced CSS for the enrollment modal and grades table for improved user experience.
> Add enrollment modal and subject grading functionality

- src/TeacherPages/EnrollmentRequests.js
- src/TeacherPagesCss/EnrollmentRequests.css
- Updated the validateStudent function to include sectionId for enrollment validation.
- Added a section selector in the enrollment modal, allowing users to choose a section based on the student's grade level.
- Implemented fetching of available sections and default selection logic.
- Enhanced CSS for the section selector and related messages for improved user experience.
> Enhance enrollment request handling with section selection

- backend/server.js
- src/TeacherPages/AttendanceManagement.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/ScheduleManagement.js
- src/TeacherPages/SectionList.js
- src/TeacherPages/SectionManagement.js
- src/TeacherPages/StudentManagement.js
- src/TeacherPages/SubjectsManagement.js
- src/TeacherPages/Teacher_SchedulePage.js
- Updated backend routes to fetch schedules, sections, and students based on user roles, improving role-based access and data retrieval.
- Implemented logic to retrieve employee IDs and handle queries for teachers and students more efficiently.
- Enhanced frontend components to utilize role-based endpoints for fetching data, ensuring that teachers and advisers can access relevant information based on their roles.
- Improved error handling and logging for better debugging and user experience.
> Enhance teacher and student management features

- backend/server.js
- src/TeacherPages/BrigadaEskwela.js
- Implemented a POST endpoint to add remarks for students in the Brigada Eskwela program, ensuring proper validation for studentId and remarks.
- Added a PUT endpoint to update student attendance status, allowing for attendance to be marked as present or absent.
- Updated the frontend to handle attendance updates and remarks submission, improving user interaction and data management for teachers.
> Add attendance and remarks functionality for Brigada Eskwela

- src/CssFiles/headbar.css
- src/Utilities/HeadBar.js
- Added CSS variables for light and dark themes in headbar.css to enhance theme management.
- Refactored HeadBar.js to include a theme toggle button, allowing users to switch between light and dark modes.
- Updated styles in headbar.css to utilize CSS variables for improved maintainability and consistency across themes.
> Implement theme toggle functionality and update headbar styles

- backend/server.js
- src/TeacherPages/EnrollmentRequests.js
- Updated SQL query in server.js to include school_year_id for better data context.
- Refactored fetchSubjectsAndGrades function in EnrollmentRequests.js to use Promise.all for concurrent API calls, improving performance.
- Adjusted state management to handle subjects and grades more effectively, ensuring accurate display in the enrollment modal.
- Modified rendering logic to reflect updated data structure for grading information.
> Enhance student enrollment data retrieval and display

- backend/server.js
- src/App.js
- src/RoleSidebars/RegistrarSideBar.js
- src/StudentPages/Student_GradesPage.js
- src/TeacherPages/BrigadaEskwela.js
- src/TeacherPages/EnrollStudentManagement.js
- src/TeacherPages/SectionList.js
- src/TeacherPagesCss/EnrollStudentManagement.css
- Modified SQL queries in server.js to improve enrollment status retrieval.
- Added new route for student enrollment management in App.js.
- Updated RegistrarSideBar.js to include the new enrollment route in navigation.
- Enhanced error handling in Student_GradesPage.js for better user feedback.
- Refactored SectionList.js to streamline data fetching and improve role-based access.
- Fixed minor issues in BrigadaEskwela.js to ensure student data is fetched correctly.
> Update student enrollment and grades handling

- backend/server.js
- src/StudentPages/Student_EnrollmentPage.js
- src/TeacherPages/EnrollStudentManagement.js
- src/TeacherPages/StudentManagement.js
- Updated the apply enrollment endpoint to use studentId instead of userId for fetching student data.
- Enhanced the enroll-elective endpoint to include userId in the request body.
- Introduced a new GET endpoint for applying enrollment with filters for searchID, searchTerm, grade, section, and school_year.
- Updated the Student_EnrollmentPage and EnrollStudentManagement components to accommodate the new enrollment logic and improve user feedback.
- Adjusted the status display for students to show 'inactive' when no active status is present.
> Refactor enrollment handling and add new apply enrollment endpoint

- src/TeacherPages/ElectiveRequest.js
- src/TeacherPagesCss/EnrollmentRequests.css
- Introduced a modal for displaying elective details and confirming approval for selected students.
- Updated the approveElective function to show the modal instead of directly calling the API when approving an elective.
- Added mock elective details for display in the modal.
- Enhanced CSS for modal actions to improve layout and styling.
> Add elective approval modal and enhance elective handling

- src/CssFiles/sidebar.css
- Introduced CSS variables for sidebar background, text, and hover states to support light and dark themes.
- Updated sidebar styles to utilize these variables for consistent theming across components.
- Improved hover and active states for buttons and submenu items to enhance user experience.
> Enhance sidebar styling with CSS variables for improved theming

- backend/server.js
- src/TeacherPages/EnrollStudentManagement.js
- src/TeacherPages/ScheduleManagement.js
- src/TeacherPages/StudentManagement.js
- src/TeacherPages/TeacherManagement.js
- src/TeacherPagesCss/EnrollStudentManagement.css
- Updated the student enrollment process to include grade level handling and improved error management.
- Added functionality to trigger a cron job for leveling up students based on their current grade.
- Introduced a new API endpoint to fetch assigned subjects for teachers based on their role.
- Enhanced the EnrollStudentManagement component to support grade level updates during enrollment.
- Improved the ScheduleManagement component to dynamically fetch and display subject teachers.
- Refactored the StudentManagement component to trigger the cron job after fetching students.
- Updated CSS styles for better usability and layout in the enrollment management interface.
> Enhance student enrollment and management features

- src/TeacherPages/TeacherManagement.js
- src/TeacherPagesCss/TeacherManagement.css
- Updated modal structure and styles for the Assign Section and Assign Subject modals to enhance usability.
- Introduced new CSS classes for better styling and layout consistency.
- Simplified button interactions and improved visual feedback for selected items.
- Enhanced form field labels and select elements for better accessibility and clarity.
> Refactor Teacher Management modals for improved UI and accessibility

- backend/server.js
- src/TeacherPages/StudentManagement.js
- src/TeacherPages/TeacherManagement.js
- Updated the student management component to handle section_id updates and ensure proper data formatting.
- Improved error handling and validation for student data during archiving.
- Enhanced teacher management to fetch sections based on the selected school year and improved UI for assigned subjects and sections.
- Refactored API calls to streamline data retrieval and updates for schedules and teacher-subject associations.
> Enhance student and teacher management features

- backend/server.js
- Updated SQL query to use COALESCE for better handling of subject names based on elective status.
- Enhanced JOIN conditions for clarity and performance.
- Improved formatting and readability of the query structure.
> Refactor schedule query for sections to improve data retrieval

- backend/server.js
- src/TeacherPages/AttendanceManagement.js
- src/TeacherPages/BrigadaEskwela.js
- src/TeacherPages/EnrollmentRequests.js
- Added a new endpoint to fetch active students with filtering options in server.js.
- Updated SQL queries to include brigada details consistently across various student-related endpoints.
- Modified frontend components to utilize the new active student endpoint and adjusted attendance logic to reflect 'Attended' status.
- Enhanced section fetching logic in EnrollmentRequests to only retrieve active sections.
> Update student and section handling in backend and frontend

- backend/server.js
- src/StudentPages/Student_EnrollmentPage.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/TeacherManagement.js
- src/Utilities/ProfilePage.js
- Updated student information update logic to include section_id in the enrollment table.
- Modified queries to ensure section_id is considered when fetching subjects and grades.
- Added email address field to teacher management and ensured it is handled in the backend.
- Adjusted profile page to display the correct email address for users.
- Improved error handling and validation for various endpoints related to student and teacher data.
> Enhance student and enrollment management in backend and frontend

- backend/server.js
- src/StudentPages/Student_EnrollmentPage.js
- Updated the backend to fetch section_id for students before checking elective status and enrollment data.
- Enhanced SQL queries to ensure accurate retrieval of subjects based on section_id and user_id.
- Modified the frontend to handle the new structure of elective status, including enrollment status and elective existence.
- Improved conditional rendering of buttons based on the updated elective status response.
> Refactor elective and enrollment status handling in backend and frontend

- backend/server.js
- src/StudentPages/Student_AttendancePage.js
- src/assets/sqldump/EMPTYTESTLATEST-3.sql
- Implemented new API endpoints for fetching student attendance data, including attendance records for specific dates.
- Enhanced SQL queries to retrieve detailed attendance information, including subject names, teacher details, and attendance status.
- Updated the Student_AttendancePage component to display attendance data with improved logging and error handling.
- Adjusted the display of attendance records to show schedule days and removed unnecessary remarks field.
> Add attendance endpoints in server.js and enhance Student_AttendancePage

- src/TeacherPages/PromotionReport.js
- src/reports/sf1.js
- Updated the PromotionReport component to use section_id as the key for section options.
- Refactored the SF1 component to utilize useLocation for better state management and to dynamically fetch class list data based on selected school year, grade, and section.
- Enhanced student data handling by replacing hardcoded values with dynamic data retrieval and improved error handling during API calls.
- Adjusted the display of student information to align with the new data structure, including changes to field names and added fallback values for missing data.
> Refactor PromotionReport and SF1 components for improved data handling

- backend/server.js
- src/TeacherPages/PromotionReport.js
- src/reports/early_enrollment.js
- src/reports/roster.js
- Added a new API endpoint for fetching student statistics, including gender breakdown and total counts.
- Implemented dynamic data retrieval in the EarlyEnrollment and Roster components, utilizing the new endpoint for improved enrollment data handling.
- Refactored the Roster component to handle API responses more robustly, including error handling and loading states.
- Updated the PromotionReport component to use section_id for section options, improving data consistency.
- Adjusted the display of student information in the Roster component to align with the updated data structure.
> Enhance student statistics and roster functionality

- backend/server.js
- src/TeacherPages/PromotionReport.js
- src/reports/form_137.js
- src/reports/form_138.js
- src/reports/sf6.js
- Updated the '/api/student/details' endpoint to include additional student information such as LRN, home address, and formatted birthdate.
- Introduced new endpoints for fetching student grades and attendance, improving the data structure for report generation.
- Refactored the PromotionReport component to validate inputs more effectively and streamline navigation to report generation pages.
- Enhanced the Form137 and Form138 components to utilize the updated API responses, ensuring accurate display of student data and academic records.
- Improved the SF6 report generation to dynamically fetch and display promotion statistics based on grade level and school year.
> Enhance student data retrieval and reporting features

- backend/server.js
- src/CssFiles/sf2.css
- src/TeacherPages/PromotionReport.js
- src/reports/sf2.js
- src/reports/sf4.js
- Added a new API endpoint '/api/sf2-attendance' to retrieve daily attendance data for students based on school year and date.
- Updated the PromotionReport component to include month and section selection for generating attendance reports.
- Enhanced the SF2 report to display detailed attendance data, including present, absent, and tardy counts for each student.
- Improved CSS styles for the SF2 report layout and added guidelines for attendance reporting.
> Implement SF2 Daily Attendance Report feature

- backend/server.js
- src/CssFiles/sf2.css
- src/TeacherPages/PromotionReport.js
- src/reports/sf2.js
- Added a new API endpoint '/api/sf2-combined' to retrieve combined attendance data for students based on month, grade level, section, and year.
- Introduced a new API endpoint '/api/school_year/section_name' to fetch section names and school year details.
- Updated the SF2 report component to display attendance data with improved structure and styling.
- Enhanced CSS for attendance status representation, including styles for present, absent, tardy, and truant statuses.
- Refactored the PromotionReport component to include year in attendance report generation.
> Implement SF2 Combined Attendance Report feature

- backend/server.js
- src/TeacherPages/ElectiveRequest.js
- src/TeacherPages/EnrollmentRequests.js
- src/assets/sqldump/EMPTYTESTLATEST-5.sql
- Added modal for confirming rejection of elective requests in ElectiveRequest and EnrollmentRequests components.
- Updated state management to handle rejection actions, including setting the selected student for rejection.
- Refactored filter application logic to send filter parameters to the backend instead of client-side filtering.
- Removed commented-out code in server.js related to school year filtering for cleaner code.
> Implement elective rejection functionality in TeacherPages

- src/TeacherPages/EnrolledStudents.js
- src/TeacherPagesCss/EnrolledStudents.css
- Added state management for sections, selectedSection, and studentToEdit to facilitate section changes for enrolled students.
- Introduced fetchSections function to retrieve section data based on the current school year.
- Enhanced the UI to include a modal for changing student sections, with appropriate state updates and error handling.
- Updated student data handling to reflect section changes in both local state and backend.
- Improved styling for the modal and student information display, ensuring a better user experience.
> Implement section management in EnrolledStudents component

- src/TeacherPages/ElectiveRequest.js
- Expanded role checks to include 'grade_level_coordinator' for viewing options, enhancing functionality for users with this role.
- Improved logging for better debugging and tracking of user roles and student statuses.
> Update role-based access in ElectiveRequest component

- src/TeacherPages/SectionManagement.js
- Changed room number validation regex to enforce a 1-3 digit numeric format instead of alphanumeric with a maximum of 10 characters.
- Updated error messages and placeholders to reflect the new validation criteria for better user guidance.
> Update room number validation in SectionManagement component

- backend/server.js
- src/CssFiles/form_137.css
- src/CssFiles/form_138.css
- src/TeacherPages/PromotionReport.js
- src/reports/class_honor_roll.js
- src/reports/class_list.js
- src/reports/early_enrollment.js
- src/reports/form_137.js
- src/reports/form_138.js
- src/reports/good_moral.js
- src/reports/nutritional_report.js
- src/reports/quarterly_assessment.js
- src/reports/roster.js
- src/reports/sf1.js
- src/reports/sf2.js
- src/reports/sf5.js
- src/reports/sf6.js
- Implemented new API endpoints to fetch adviser and principal details for various reports, enhancing the data displayed in the reports.
- Updated report components to include adviser and principal names in the signature sections, improving the completeness of the reports.
- Adjusted the CSS for signature lines in forms to ensure consistent styling across different reports.
> Add adviser and principal information retrieval to reports

- src/TeacherPages/GradesManagement.js
- src/TeacherPagesCss/GradesManagement.css
- Introduced a new state to manage activity logs for students.
- Implemented a function to fetch and display grade activity logs, sorted by timestamp.
- Added a dedicated section in the UI to show the logs with appropriate styling.
- Updated CSS to style the grade logs section and its elements for better user experience.
> Add grade activity logs feature in Grades Management

- backend/server.js
- src/RoleSearchFilters/StudentSearchFilter.js
- src/TeacherPages/GradesManagement.js
- src/TeacherPages/StudentManagement.js
- Added functionality to filter students by archive status in the StudentSearchFilter component.
- Updated the GradesManagement component to fetch and display grade activity logs, including user actions and timestamps.
- Improved the archiving process in StudentManagement, allowing for unarchiving and better user feedback through alerts.
- Refactored code for clarity and maintainability, ensuring a smoother user experience across the application.
> Enhance student management and grades features

- src/TeacherPages/GradesManagement.js
- Updated the fetchGradeActivityLogs function to use async/await for improved readability and error handling.
- Removed redundant comments and streamlined the logic for fetching and setting activity logs.
- Enhanced the useEffect hook to properly handle loading and error states when fetching grades and activity logs for selected students.
> Refactor grade activity logs fetching in GradesManagement component
